server:
  port: 8080
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: UAA
          uri: http://127.0.0.1:8081/
          predicates:
            - Path=/UAA/**